---
# add_zypper_repository/tasks/main.yml

#
# compatibility with older versions
#
- name: 'set fact for enabling the repository'
  ansible.builtin.set_fact:
    compat_repository_enabled: 'yes'
  when:
    - 'repository_enabled == "1"'

- name: 'set fact for disabling the repository'
  ansible.builtin.set_fact:
    compat_repository_enabled: 'no'
  when:
    - 'repository_enabled == "0"'

- name: 'set fact for enabling autorefresh'
  ansible.builtin.set_fact:
    compat_autorefresh_enabled: 'yes'
  when:
    - 'autorefresh_enabled == "1"'

- name: 'set fact for disabling autorefresh'
  ansible.builtin.set_fact:
    compat_autorefresh_enabled: 'no'
  when:
    - 'autorefresh_enabled == "0"'

- name: 'set fact for not disabling gpgcheck'
  ansible.builtin.set_fact:
    compat_gpgcheck_disabled: 'no'
  when:
    - 'gpgcheck == "1"'

- name: 'set fact for disabling gpgcheck'
  ansible.builtin.set_fact:
    compat_gpgcheck_disabled: 'yes'
  when:
    - 'gpgcheck == "0"'

#
#
#
- name: "Add the zypper repository {{ repository_name }}"
  community.general.zypper_repository:
    repo: "{{ repository_baseurl }}"
    name: "{{ repository_name }}"
    enabled: "{{ compat_repository_enabled }}"
    autorefresh: "{{ compat_autorefresh_enabled }}"
    state: 'present'
    runrefresh: 'yes'
    priority: "{{ priority }}"
    disable_gpg_check: "{{ compat_gpgcheck_disabled }}"
    auto_import_keys: "{{ auto_import_keys }}"
